<?php

function easy_newsletter_menu() {
    $items = array();

    $items['newsletter/easy-newsletter'] = array( //this creates a URL that will call this form at "examples/form-example"
        'title' => 'easy-newsletter', //page title
        'description' => 'A form to mess around with.',
        'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
        'page arguments' => array('easy_newsletter_form'), //put the name of the form here
        'access callback' => TRUE
    );

    return $items;
}

function easy_newsletter_form($form, &$form_state) {

    $form['email'] = array(
        '#type' => 'textfield', //you can find a list of available types in the form api
        '#title' => 'What is Your email?',
        '#size' => 10,
        '#maxlength' => 10,
        '#required' => TRUE, //make this field required
    );

    $form['name'] = array(
        '#type' => 'textfield', //you can find a list of available types in the form api
        '#title' => 'What is Your name?',
        '#size' => 10,
        '#maxlength' => 10,
        '#required' => TRUE, //make this field required
    );
    $form['submit_button'] = array(
        '#type' => 'submit',
        '#value' => t('Click Here!'),
    );

    return $form;
}

function easy_newsletter_form_validate($form, &$form_state) {
    if (!($form_state['values']['price'] > 0)){
        form_set_error('price', t('Price must be a positive number.'));
    }
}

function easy_newsletter_form_submit($form, &$form_state) {
}
?>